### ISSUE TITLE
my-slider-v2 doesn't exist

### ISSUE THREAD

**Issue by Djeloan** [CollotsSpot/Conditional-Media-Player#1]
Hi, first of all i want to thank you for this card, i love the look of it!

Now, i followed all your steps and when i play media the card shows up but i get the following error:

> Custom element doesn't exist: my-slider-v2

i guess we need to install 1 more repo to HACS but i'm not sure which one is the right?

![Screenshot 2024-07-03 204831](https://github.com/CollotsSpot/Conditional-Media-Player/assets/5245733/6ea34d59-2f92-4436-9023-7d4a2bc56c33)

**Comment by CollotsSpot** [comment]
Oh snap! I missed a component! No worries it's My Cards Bundle:

https://github.com/AnthonMS/my-cards

I will add to the readme

Thank for letting me know!
